site_name: Panda Docs
site_description: Documentation for Panda
site_author: Pirsani Labs
nav:
  - Home: index.md
  - Pendahuluan: pendahuluan.md
  - Panduan Pengguna: panduan-pengguna.md
  - Panduan Pengembang: panduan-pengembang.md
  - Database: database.md
  - Arsitektur dan Implementasi Nextjs: arsitektur-implementasi.md
  - Panduan Pemeliharaan: panduan-pemeliharaan.md
# theme: readthedocs
theme:
  name: material # material
  favicon: favicon.ico
plugins:
  - search
  # - pdf-export
  - exporter
markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css